sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: a7gd4fwoPOb+kp99maLWszRdKFK7uikBvbZWZdWVPcWF1ikMVjWHOyg/mr98Pk42Y9doswiow2IJlPcuN8M0MDbPbr5yDL0VzOQxO17GrdBuTjnQzjTiS+ub4yGJZ5YEx6yAwTPO3O4immTLOEj+Eu7nvjYdizCKHgOHJMkY7T7lYRoNAAsWKh/neTMIhOF+0833/K4ynuDAv0PaWCWOM5ZbZXaxg/crzYLzdnDraHy5bp1A1W7ywy/ZDatlxlUEPDW8f17WUQyHyrsYjAjt34hVU9XPlwMeavgLcTELUclxWVG1RY9UV1Z7bLiwH/3hTi7yAaD/kZoIcRyVG9a7fZx2kn3vfa7bgssNOZZezFcsOBdrjf1wa09tZcg+ON8RrB5ITUlQRC6ZEgY/w3NKwo7nt8ii6xUusrqORDr24FVAwWixEd67uXcFcOk45jYP+o7EojfT8W1K68g4Zn3OhqfhEyeMOIITbqMCT3/IVs274uzmf+Kv2YonHG97LVWBDNzn/CU+Niqu6s8AceeV8s+CvLun91n5G29shAaq5iMvG0Etbc2qA7sVHqeX8wAYmZB8zSZPMZ5yxNtsteaLxh3rnpsvV5+IF9HShF4XU2B6OLiN8e+pLJjK7PEt7cja4Lr4G/ufro9swAM5YN24kNKDGHJFs4z09bq4zELxtV8=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Stage-Land_858
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy